name: microsoft_graph_http
description: A companion package for the `microsoft_graph` package. Includes the `IHttpClient` implementation for the Dart `http` package.
version: 0.0.13
homepage: https://github.com/dmytro-glynskyi/microsoft-graph-http
author: Dmytro Glynskyi <dmytro.glynskyi@gmail.com>
environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ^0.12.0
  microsoft_graph: ^0.0.13

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
